import { Box, Container, Flex, Heading, Image, useColorModeValue } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Section from '@/components/section';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container>
        <Box borderRadius='lg' bg={useColorModeValue('whiteAlpha.500', 'whiteAlpha.200')} p='3' mb='6' alignItems='center'>
          Hello, I&apos;m a full-stack developer based in Japan!
        </Box>
        <Box display={{ md: 'flex' }}>
          <Box flexGrow='1'>
            <Heading as='h2' variant='padding-title'>
              Kameda Shunsuke
            </Heading>
            <p>Digital Craftzman (Artist / Developer / Designer)</p>
          </Box>
          <Flex flexShrink={0} mt={{ base: 4, md: 0 }} ml={{ md: 6 }} justifyContent={'center'}>
            <Image
              borderColor='whiteAlpha.800'
              borderWidth={2}
              borderStyle='solid'
              maxWidth='100px'
              display='inline-block'
              borderRadius='full'
              src='image/IMG_4331.JPG'
              alt='Profile Image'
            />
          </Flex>
        </Box>
        <Section delay={'0.1s'}>
          <Heading as='h3' variant='section-title'>
            Work
          </Heading>
          <p>Paragraph</p>
        </Section>
      </Container>
    </div>
  );
};

export default Home;
