import { Box, Container, Heading } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container>
        <Box borderRadius='lg' bg='red' p='3' mb='6' alignItems='center'>
          Hello, I&apos;m a full-stack developer based in Japan!
        </Box>
        <Box display={{ md: 'flex' }}>
          <Box flexGrow='1'>
            <Heading as='h2' variant='padding-title'>
              Kameda Shunsuke
            </Heading>
            <p>Digital Craftzman (Artist / Developer / Designer)</p>
          </Box>
        </Box>
      </Container>
    </div>
  );
};

export default Home;
